<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Security Alert</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: Arial, sans-serif;
            text-align: center;
            padding-top: 50px;
        }
        h1 {
            color: #ff0000;
        }
        .message {
            font-size: 1.2em;
            margin-top: 20px;
        }
        .countdown {
            font-size: 2em;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <h1>⚠️ SECURITY ALERT ⚠️</h1>
    <div class="message">
        Your Instagram account has been compromised!
    </div>
    <div class="message">
        Hacker: "I have access to your account. Change your password immediately!"
    </div>
    <div class="countdown" id="countdown">5</div>
    <div class="message">
        Redirecting to Instagram Security Center in <span id="seconds">5</span> seconds...
    </div>

    <script>
        let timeLeft = 5;
        const countdownElement = document.getElementById('countdown');
        const secondsElement = document.getElementById('seconds');

        const countdown = setInterval(() => {
            timeLeft--;
            countdownElement.textContent = timeLeft;
            secondsElement.textContent = timeLeft;

            if (timeLeft <= 0) {
                clearInterval(countdown);
                window.location.href = 'https://www.instagram.com/accounts/login/';
            }
        }, 1000);
    </script>
</body>
</html>
